# -*- coding: utf-8 -*-
"""Practica 1 DA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dvWpkH4EsHiXyAGrvFC57zQI8Ljr2KYU
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Crear un DataFrame con datos de ventas
data = {
    'Mes': ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
    'Ventas': [2000, 2200, 2500, 2700, 3000, 2800, 3500, 3700, 3300, 3100, 3200, 3400],
    'Costos': [1500, 1600, 1700, 1800, 1900, 2000, 2100, 2200, 2300, 2400, 2500, 2600]
}

df = pd.DataFrame(data)

# Calcular el beneficio
df['Beneficio'] = df['Ventas'] - df['Costos']

# Calcular el porcentaje de beneficio
df['Porcentaje Beneficio'] = (df['Beneficio'] / df['Ventas']) * 100

# Configurar el estilo de Seaborn
sns.set(style="darkgrid")

# Crear una figura y ejes para las subplots
fig, axs = plt.subplots(2, 1, figsize=(12, 10))

# Gráfico de ventas y costos
sns.lineplot(data=df, x='Mes', y='Ventas', marker='o', ax=axs[0], label='Ventas', color='blue')
sns.lineplot(data=df, x='Mes', y='Costos', marker='o', ax=axs[0], label='Costos', color='red')
axs[0].set_title('Ventas y Costos Mensuales')
axs[0].set_xlabel('Mes')
axs[0].set_ylabel('Monto')
axs[0].legend()

# Gráfico de porcentaje de beneficio
sns.barplot(data=df, x='Mes', y='Porcentaje Beneficio', palette='viridis', ax=axs[1])
axs[1].set_title('Porcentaje de Beneficio Mensual')
axs[1].set_xlabel('Mes')
axs[1].set_ylabel('Porcentaje (%)')

# Ajustar el diseño y mostrar los gráficos
plt.tight_layout()
plt.show()